export type Scholar = {
  uuid: string;
  username: string;
  email: string;
  englishName: string;
  khmerName: string;
  gender: "Male" | "Female";
  status: string;
  dob: string;
  role: string;
  university: string;
  province: string;
  currentAddress: string;
  nickname: string;
  bio: string;
  avatar: string;
  phoneFamilyNumber: string;
  isPublic: boolean;
  quote: string;
};