import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter, Koh_Santepheap } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";
import I18nProvider from "@/lib/I18nProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const koh = Koh_Santepheap({
  variable: "--font-koh",
  weight: "400",
  subsets: ["khmer"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "EXSTAD",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // await cookies() per Next.js guidance to avoid sync-dynamic-apis warning
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get("locale")?.value;

  // internal locale keys use 'kh' but the HTML lang for Khmer should be 'km'
  const internalLocale = cookieLocale === "kh" ? "kh" : cookieLocale ?? "en";
  const htmlLang = internalLocale === "kh" ? "km" : internalLocale;

  return (
    <html lang={htmlLang} suppressHydrationWarning>
      <body
        className={`${inter.variable} ${koh.variable} antialiased relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <I18nProvider initialLocale={internalLocale}>
              <Navbar />
              {children}
            </I18nProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
