
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter, Koh_Santepheap } from "next/font/google";
import "./globals.css";
import Providers from "@/services/store/Providers";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";
import I18nProvider from "@/lib/I18nProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const koh = Koh_Santepheap({
  variable: "--font-koh",
  weight: "400",
  subsets: ["khmer"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "EXSTAD",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get("locale")?.value;

  const internalLocale = cookieLocale === "kh" ? "kh" : cookieLocale ?? "en";
  const htmlLang = internalLocale === "kh" ? "km" : internalLocale;

  // Fallback empty strings for font variables to avoid hydration mismatch
  // const interVariable = inter.variable ?? "";
  // const kohVariable = koh.variable ?? "";

  return (
    <html lang={htmlLang} suppressHydrationWarning>
      <body
        className={`${inter.variable} ${koh.variable} antialiased relative h-[200vh] bg-background-white-smoke`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <I18nProvider initialLocale={internalLocale}>
              <Navbar />
              {children}
            </I18nProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
